name: Build & test

on: [push, pull_request]

jobs:
  main:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build
    - name: Test
      run: dotnet test
    - name: Nuget Release
      with:
        nuget_secret: ${{secrets.NUGET_API_KEY_TEST}}
      run: ls
